### ISSUE TITLE
Part of logo in README can't be seen.

### ISSUE THREAD

**Issue by TobiasSN** [bitphoenixsoftware/the-peacenet#1]
Because 'the' in the logo is white, it can't be seen because the background is too.

I suggest changing it to gray, so that it looks good on both the regular theme and for people who use a dark mode extension.

**Comment by alkalinethunder** [comment]
Simple fix is to use Dark Reader.

In all seriousness though, I have a black version of the logo so I'll replace it with that soon.

**Comment by TobiasSN** [comment]
That will just create a problem for people with Dark Reader.

**Comment by alkalinethunder** [comment]
Yeah but I'm too lazy to open Gimp.

**Comment by TobiasSN** [comment]
I can do it for you.
