### ISSUE TITLE
Tutorial didn't give command to download file

### ISSUE THREAD

**Issue by Mik2G** [bitphoenixsoftware/the-peacenet#10]
The tutorial didn't give me a way to download the file I need to my (ig) computer. I've tried running "download", but that crashes the game.

**Comment by alkalinethunder** [comment]
The tutorial missions in the game are currently written against outdated lore and gameplay mechanics that have either been removed in the latest codebase or are still being worked on.

I'd advise waiting for the release of 0.3.0 on itch.io before playing through the game's story as these bugs are only typically present during refactors that aren't fully finished yet.
