### ISSUE TITLE
Peacenet fails to compile on UE4.22 with LowEntry-ExtendedStandardLibrary

### ISSUE THREAD

**Issue by TobiasSN** [bitphoenixsoftware/the-peacenet#3]
**OS Version:** macOS Mojave 10.14.4
**Unreal Engine version:** 4.22

**How to reproduce**

1. Clone the repository.
2. Open Unreal.
3. Browse for the project and open it.
4. When asked if you wanna convert it, choose yes.

Error: https://pastebin.com/kaTkRAUt

**Comment by alkalinethunder** [comment]
This is a known issue with 4.21 and 4.22.  The issue is with that `LowEntry-ExtendedStandardLibrary` plugin, it needs to be updated before we can go to 4.21 or 4.22.  I'm going to do that over the weekend since the indev build of the game is out.

The extension currently needs 4.20.3.

**Comment by TobiasSN** [comment]
Guess I'll wait for that then.

**Comment by alkalinethunder** [comment]
I don't know if the Epic Games Launcher runs on macOS but you should be able to update the plugin in there unless I added the plugin using git rather than UE marketplace.

**Comment by alkalinethunder** [comment]
I was able to get the game to COMPILE on 4.22.0 by removing the bad plugin from the repo.  But this also means that you need to install the LowEntry Extended Standard Library through the Epic launcher/UE4 marketplace otherwise some Blueprints that use the library won't build.
