### ISSUE TITLE
Port over all GUI programs.

### ISSUE THREAD

**Issue by alkalinethunder** [bitphoenixsoftware/the-peacenet#4]
A lot of the GUI programs in the game haven't yet been ported over.  The game's windowing system as well as user/kernel-land are both unfinished but work well enough to begin porting some of the programs over.  The sooner we can get this done, the more we can focus on the rest of the game.

**Programs to port:**

 - [ ] File Manager - so we can browse the in-game disk
 - [ ] Manual - to give players an easier way to learn about the game.
 - [x] Terminal - most hacking is done in here, and it gives players access to all of the command-line tools in the game.
 - [ ] Icedog Mail Viewer - gives us access to the mission system which will be ported over later.

**Useful tips**

 - GUI programs are defined using XML.  The only C# required for GUI programs are their code-behind, for handling events fired by the GUI toolkit (such as user clicking a specific button).
 - Existing programs can be used as examples of the XML system in the game.
 - If you have trouble with the code-behind and event handling, don't focus on that.  Focus on the layout of the UI rather than functionality - functionality can always be added later on.
 - When dealing with the code-behind, you have access to the current Peacegate user land, as well as the Window your program exists in.  You can find and interact with controls in your UI as  well as perform actions in the user's Peacegate from your code-behind.

**Comment by alkalinethunder** [comment]
Minus some performance issues, I have already finished the Terminal and it functions fully.

**Comment by TheDarkBomber** [comment]
Icedog? Sounds awfully similar to another name, can't remember but it was like a burning fox or something? Oh yes, Mozilla ThunderBird!

**Comment by alkalinethunder** [comment]
That was the point the whole time. :)

**Comment by TheDarkBomber** [comment]
I always knew you loved to burn foxes.  Damnit, ThunderBird!

**Comment by alkalinethunder** [comment]
I will refrain from discussing anything that can be misread by my eyes as me "loving to burn Lyfox" on my public GitHub.  I think you should do the same.  Thank you. :)

**Comment by alkalinethunder** [comment]
Closed - monogame development is abandoned.
