### ISSUE TITLE
[Discussion] Main Menu Design

### ISSUE THREAD

**Issue by alkalinethunder** [bitphoenixsoftware/the-peacenet#7]
I guess now it's time to discuss what the game's Main Menu should look like and what features it should have.  In the Unreal builds we had simple access to creating a new game, loading the existing game and adjusting game settings.

In #6 we are implementing the game's **save system**, this time supporting neat things like multiple save files and a *profile* that can contain other data.  So naturally we need a main menu that supports all that.  But how should it look? How should it be laid out?

Key features of an ideal menu would be

 - create new game saves
 - list existing game saves
 - allow deletion of game saves
 - allow loading of game saves
 - access to game settings (resolution, GUI scale, etc)
 - have support for extensions if we decide to add support for player-created mods, like Hacknet  has.
 - allow user to exit the game

Those are the main features I can think of.  For now I'm just going to do a barebones layout in the menu so I can get into the rest of the game and keep porting the backend, but eventually we should look at fleshing the menu out and making it look cool.

**Comment by alkalinethunder** [comment]
Currently my idea is to have it look sorta like Windows 10's login sscreen.  So "users", or agents, are listed in the lower left, there's a section in the middle for the "selected" agent that shows info about it, and in the lower right there's buttons to quit the game and access settings.

**Comment by NarodGaming** [comment]
Whilst I do like the Windows 10-esque design, you could go for something slightly hybrid / retro. For example, in Windows XP to 7 (I think not Windows 8), the choice was in the middle of the screen at first, after that, possibly move the other options to the bottom left?

Windows 10-esque idea still sounds pretty good, especially if it could remember which the last account was.

**Comment by alkalinethunder** [comment]
I'm also wondering what the menu should look like when there are no existing Agents for the player to select.  Can't decide if I want to have the game skip the menu and have the player create a new agent through some sort of story intro or what.

**Comment by NarodGaming** [comment]
I'd probably suggest a "New User" option in the middle of the screen that asks for whatever information is needed, which goes into a "This won't take long" sort of loading thing, that then goes in to story intro.

**Comment by alkalinethunder** [comment]
Closed - monogame development is abandoned.
